#########################################################################
#       This script plots the turbulent magnetic field                  #
#       generated by cppstructure.exe                                   #
#                                                                       #
#       Written by Odd-Einar C. Nervik                                  #
#########################################################################

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import Normalize

bfield = np.loadtxt('cpp_bfield/turbulence.dat')               # Reads the data from the generated file.

colors =  np.arctan2(bfield[:,3], bfield[:,4])      # Decides color based on the xy-plane angle

norm = Normalize()
norm.autoscale(colors)                              # Normalizes the colors to the given range of "colors"

fig = plt.figure()
ax = fig.gca(projection='3d')

colormap = cm.get_cmap('seismic')                   # Picks the desired colormap

ax.quiver(bfield[:,0], bfield[:,1], bfield[:,2], bfield[:,3], bfield[:,4], bfield[:,5], length = 0.5, normalize = False, color=colormap(norm(colors)))

plt.xlabel('Bx')
plt.ylabel('By')
ax.set_zlabel('Bz')

plt.show()